clearItemCargoGlobal this; 
clearWeaponCargoGlobal this; 
clearMagazineCargoGlobal this; 
this addMagazineCargoGlobal ["Chemlight_green",100]; 
this addMagazineCargoGlobal ["Chemlight_red",100]; 
this addMagazineCargoGlobal ["Chemlight_yellow",100]; 
this addItemCargoGlobal ["NVGoggles",20]; 
this addItemCargoGlobal ["ToolKit",100]; 
this addItemCargoGlobal ["B_UavTerminal",4]; 
this addWeaponCargoGlobal ["Laserdesignator",10]; 
this addMagazineCargoGlobal ["Laserbatteries",20]; 
this addWeaponCargoGlobal ["BWA3_Vector",20]; 
this addItemCargoGlobal ["BWA3_ItemNavipad",20];